"""Polygraphy backend — failure class (B), accuracy divergence.

Polygraphy is NVIDIA's model-comparison tool. It runs the same inputs through
two "runners" (TensorRT vs ONNX Runtime, FP32 vs INT8, x86 vs ARM) and reports
elementwise differences per output tensor. Its comparison output is the richest
accuracy-divergence signal any vendor emits, and it is *already* cross-vendor —
which is why it gets its own parser rather than living inside `tensorrt.py`.

Naming note: "backend" here means "which parser + rule family", not "which
silicon". A Polygraphy log describes a comparison BETWEEN backends, so it
belongs to neither one.

WHY THIS PARSER IS SHAPED DIFFERENTLY FROM tensorrt.py
The TensorRT parser is stateless: every failure is fully described by one line.
Polygraphy's output is *block-structured* — a per-tensor block whose header
names the tensor, with later lines inside the block (like
"Minimum Required Tolerance") carrying no name of their own. So this parser
tracks the current block to attribute those lines. Same grounding rule applies:
record only what is in the log; interpretation happens in the rule KB.

THE HONESTY TRAP THIS PARSER IS BUILT TO AVOID
In a passing and a failing comparison of the same model, the numeric lines
("Average Metrics", "Minimum Required Tolerance") are BYTE-IDENTICAL — only the
verdict lines differ, because tolerance is a policy, not a measurement. A parser
that treated "large max_absdiff" as evidence of failure would invent failures in
clean logs. So divergence *magnitude* facts and divergence *verdict* facts are
deliberately separate kinds, and only verdicts may fire an error rule. See the
`int8_vs_fp32_pass.log` / `int8_vs_fp32_fail.log` pair in corpus/onnxruntime/.

Every signature below is verified twice: against real logs generated by
`scripts/make_divergence_corpus.py`, and against the f-strings in Polygraphy's
own source (polygraphy/comparator/compare.py and comparator.py) so the patterns
match the emitter rather than one sample. Source lines are cited per signature.
"""

from __future__ import annotations

import re
from pathlib import Path
from typing import Any, Callable

from .base import Backend, Fact, Facts

# Polygraphy quotes tensor names inconsistently: 'single' quotes in the
# tolerance path, `backticks` in the shape-mismatch path (compare.py lines 752
# and 720 respectively). This class matches either, so one pattern per concept
# stays sufficient.
_Q = r"['\"`]"

# ── Signature table ────────────────────────────────────────────────────────
# (kind, pattern, summary_builder). Ordered most-specific-first; the first
# match on a line wins, exactly as in the TensorRT parser.

_Sig = tuple[str, re.Pattern[str], Callable[[re.Match[str]], str]]

_SIGNATURES: list[_Sig] = [
    # ── Verdicts: the ONLY lines allowed to prove a failure ───────────────
    # Per-output divergence beyond tolerance.
    # Source: compare.py:752 f"FAILED | Output: '{out0_name}' | Difference
    # exceeds tolerance (rel={per_out_rtol}, abs={per_out_atol})"
    (
        "output_mismatch",
        re.compile(
            rf"FAILED \| Output: {_Q}(?P<output>[^'\"`]+){_Q} \| "
            r"Difference exceeds tolerance \(rel=(?P<rtol>\S+?), abs=(?P<atol>[^)]+)\)"
        ),
        lambda m: (
            f"Output '{m['output']}' diverged beyond tolerance "
            f"(rel={m['rtol']}, abs={m['atol']})"
        ),
    ),
    # Per-output comparison PASSED. Recorded (not ignored) because "this output
    # was compared and matched" is itself evidence — it's what lets a rule
    # distinguish a clean run from an unparsed one.
    # Source: compare.py:756.
    (
        "output_match",
        re.compile(
            rf"PASSED \| Output: {_Q}(?P<output>[^'\"`]+){_Q} \| "
            r"Difference is within tolerance \(rel=(?P<rtol>\S+?), abs=(?P<atol>[^)]+)\)"
        ),
        lambda m: (
            f"Output '{m['output']}' matched within tolerance "
            f"(rel={m['rtol']}, abs={m['atol']})"
        ),
    ),
    # Comparison REFUSED because shapes differ — a harness error, not an
    # accuracy problem. Kept a distinct kind so the fix differs.
    # Source: compare.py:720 (note the backticks in the original f-string).
    (
        "shape_mismatch",
        re.compile(
            rf"FAILED \| Output: {_Q}(?P<output>[^'\"`]+){_Q} \| "
            r"Will not compare outputs of different shapes"
        ),
        lambda m: f"Output '{m['output']}' not compared: the two runners' shapes differ",
    ),
    # The actual shapes, emitted on the continuation line after the above.
    (
        "shape_detail",
        re.compile(
            r"Note: Output shapes are \((?P<shape0>[^)]*)\) and \((?P<shape1>[^)]*)\)"
        ),
        lambda m: f"Compared shapes were ({m['shape0']}) and ({m['shape1']})",
    ),
    # Roll-up of every output that failed, as a Python list literal.
    # Source: compare.py:308.
    (
        "mismatched_outputs",
        re.compile(r"FAILED \| Mismatched outputs: \[(?P<outputs>.*)\]"),
        lambda m: (
            f"{len(_split_name_list(m['outputs']))} output(s) failed comparison"
        ),
    ),
    # All outputs matched.
    # Source: compare.py:310-312.
    (
        "all_outputs_matched",
        re.compile(r"PASSED \| All outputs matched \| Outputs: \[(?P<outputs>.*)\]"),
        lambda m: (
            f"All {len(_split_name_list(m['outputs']))} compared output(s) matched"
        ),
    ),
    # ── Validation (--validate): NaN / Inf in an output ───────────────────
    # Categorically worse than divergence: the model emits garbage, not
    # slightly-wrong numbers. Source: comparator.py NaN/Inf detection.
    (
        "nan_detected",
        re.compile(r"NaN Detected \| (?P<detail>.+)$"),
        lambda m: "NaN values present in an output tensor",
    ),
    (
        "inf_detected",
        re.compile(r"Inf Detected \| (?P<detail>.+)$"),
        lambda m: "Non-finite (inf) values present in an output tensor",
    ),
    (
        "validation_failed",
        re.compile(r"FAILED \| Errors detected in output: (?P<output>\S+)"),
        lambda m: f"Output '{m['output']}' failed validation (NaN/Inf check)",
    ),
    # ── Magnitude facts: measurements only, NEVER failure evidence ────────
    # How far off the values were. Present identically in passing logs.
    # Source: comparator.py:385 f"Average Metrics | {output_name}: ..."
    (
        "divergence_metrics",
        re.compile(r"Average Metrics \| (?P<output>[^:]+): (?P<metrics>.+)$"),
        lambda m: (
            f"Measured divergence for '{m['output'].strip()}': "
            f"max_absdiff={_metric(m['metrics'], 'max_absdiff')}, "
            f"max_reldiff={_metric(m['metrics'], 'max_reldiff')}"
        ),
    ),
    # The tolerance that WOULD have passed. The single most actionable number
    # in the log — it tells you how far off you actually are.
    # Source: compare.py:597.
    # NOTE on group naming: `required_tolerance` and `tolerance_setting` both
    # describe an abs/rel pair, but they mean opposite things — one is what
    # WOULD have passed, the other is what WAS demanded. They are named
    # req_*/used_* rather than abs/rel because the diagnoser resolves message
    # placeholders across all matched facts, so a shared name would let a rule
    # silently print the wrong number.
    (
        "required_tolerance",
        re.compile(
            r"Minimum Required Tolerance: (?P<stat>\w+) error \| "
            r"\[abs=(?P<req_abs>\S+?)\] OR \[rel=(?P<req_rel>[^\]]+)\]"
        ),
        lambda m: (
            f"Would have passed at abs={m['req_abs']} OR rel={m['req_rel']} "
            f"({m['stat']} error)"
        ),
    ),
    # The tolerance that WAS applied, and which error statistic was checked.
    # Source: compare.py:1166.
    (
        "tolerance_setting",
        re.compile(
            r"Tolerance: \[abs=(?P<used_abs>[^,]+), rel=(?P<used_rel>[^\]]+)\] \| "
            r"Checking (?P<stat>\w+) error"
        ),
        lambda m: (
            f"Comparison used abs={m['used_abs']}, rel={m['used_rel']} "
            f"on {m['stat']} error"
        ),
    ),
    # ── Context facts: what was compared, and the run-level outcome ───────
    # Source: compare.py:296.
    (
        "compared_output",
        re.compile(
            rf"Comparing Output: {_Q}(?P<output>[^'\"`]+){_Q} "
            r"\(dtype=(?P<dtype>\S+), shape=\((?P<shape>[^)]*)\)\)"
        ),
        lambda m: (
            f"Compared output '{m['output']}' (dtype={m['dtype']}, "
            f"shape=({m['shape']}))"
        ),
    ),
    # Pass rate across iterations. Source: comparator.py:388.
    (
        "accuracy_summary",
        re.compile(
            r"Accuracy Summary \| (?P<runner0>\S+) vs\. (?P<runner1>\S+) \| "
            r"Passed: (?P<passed>\d+)/(?P<total>\d+) iterations \| "
            r"Pass Rate: (?P<rate>[\d.]+)%"
        ),
        lambda m: (
            f"{m['passed']}/{m['total']} iteration(s) passed "
            f"({m['rate']}%): {m['runner0']} vs {m['runner1']}"
        ),
    ),
    # Whole-command verdict banner (always the last line).
    (
        "run_verdict",
        re.compile(r"(?P<verdict>PASSED|FAILED) \| Runtime: (?P<runtime>\S+)"),
        lambda m: f"polygraphy run verdict: {m['verdict']} (runtime {m['runtime']})",
    ),
]


def _split_name_list(raw: str) -> list[str]:
    """Split a Python-list-literal body into tensor names.

    Polygraphy prints `['a', 'b']`; we receive the inside (`'a', 'b'`). Names
    can contain '/' and '.' (e.g. '/layer1/layer1.0/conv1/Conv_output_0') but
    never quotes, so splitting on the quotes is unambiguous.
    """
    return [n for n in re.findall(r"""['"`]([^'"`]+)['"`]""", raw) if n]


def _metric(metrics: str, key: str) -> str:
    """Pull one `key=value` out of Polygraphy's metrics string.

    The string looks like: `max_absdiff=4.5205 (n=1), max_reldiff=256.7 (n=1)`.
    Returns "?" when absent rather than raising — a missing metric must never
    break parsing of an otherwise-good log.
    """
    m = re.search(rf"{re.escape(key)}=(\S+?)(?:\s|,|$)", metrics)
    return m.group(1) if m else "?"


class PolygraphyBackend(Backend):
    """Parses `polygraphy run` comparison output into accuracy-divergence Facts."""

    name = "polygraphy"

    def convert(self, model_path: Path, **options: Any) -> list[Path]:
        """Not applicable: Polygraphy compares models, it doesn't convert them.

        Producing these artifacts is scripted instead — see
        scripts/make_divergence_corpus.py — because a comparison needs two
        runners and a saved baseline, which doesn't fit a single-model convert().
        """
        raise NotImplementedError(
            "Polygraphy is a comparison tool, not a converter. Generate "
            "comparison artifacts with scripts/make_divergence_corpus.py."
        )

    def parse(self, artifact_path: Path) -> Facts:
        """Extract Facts from a `polygraphy run` log."""
        text = artifact_path.read_text(errors="replace")
        return self.parse_text(text, artifact_name=artifact_path.name)

    def parse_text(self, text: str, artifact_name: str = "<string>") -> Facts:
        """Parse log text directly (separated from file I/O for testability)."""
        facts: list[Fact] = []
        # Block context: "Minimum Required Tolerance" and the metric lines sit
        # inside a per-tensor block and don't repeat the tensor name, so we
        # carry the name forward from the block header. This is still recording
        # only what the log says — the association is what the indentation
        # already means.
        current_output: str | None = None

        for lineno, line in enumerate(text.splitlines(), start=1):
            for kind, pattern, summarize in _SIGNATURES:
                m = pattern.search(line)
                if m is None:
                    continue

                groups = {k: v for k, v in m.groupdict().items() if v is not None}

                # Track / attribute the enclosing comparison block.
                if kind == "compared_output":
                    current_output = groups.get("output")
                elif "output" not in groups and current_output is not None:
                    groups["output"] = current_output

                # Break the metrics blob into individual numbers so rules can
                # cite an exact measured value instead of re-parsing a string.
                if kind == "divergence_metrics":
                    for key in (
                        "max_absdiff", "max_reldiff",
                        "mean_absdiff", "mean_reldiff",
                        "median_absdiff", "median_reldiff",
                    ):
                        value = _metric(groups.get("metrics", ""), key)
                        if value != "?":
                            groups[key] = value

                # Expand list-valued lines into a usable payload.
                if kind in ("mismatched_outputs", "all_outputs_matched"):
                    names = _split_name_list(groups.pop("outputs", ""))
                    groups["outputs"] = names
                    groups["count"] = len(names)
                    # The first name is the first output Polygraphy reported —
                    # for a `--onnx-outputs mark all` run that is the earliest
                    # diverging tensor in the graph, which is the actionable one.
                    if names:
                        groups["first_output"] = names[0]

                facts.append(
                    Fact(
                        id=f"f{len(facts) + 1}",
                        kind=kind,
                        summary=summarize(m),
                        source=f"{artifact_name}:{lineno}",
                        excerpt=line.strip(),
                        data=groups,
                    )
                )
                break  # one fact per line

        return Facts(backend=self.name, artifact_path=artifact_name, facts=facts)
